### ISSUE TITLE
Modifying source in sfdx pre deploy hook (provided with an array of SourceComponent)

### ISSUE THREAD

**Issue by gitfish** [forcedotcom/source-deploy-retrieve#657]
Hi, this is just a request for clarity (wasn't sure where else to post).

An sfdx predeploy hook is provided with an array of SourceComponent. I'm able to modify the source being deployed by:
- Modifying the content at paths xml or content (or both) and writing to temp/staging paths
- Updating the content or xml (or both) paths to the temp/staging paths

The xml prop is defined as readonly, so that'd suggest this might not be the correct way to go about this. Is there any documentation on how to modify source in predeploy hooks sitting around anywhere?

Cheers.

**Comment by shetzel** [comment]
See https://github.com/salesforcecli/plugin-metadata-hook-demo/blob/master/src/hooks/predeploy/metadataReplaceDeploy.ts
